 ### Ques1-Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np
import pandas as pd
import ast 


In [2]:

array=ast.literal_eval(input('Enter the array'))
array
n=len(array)



Enter the array[1,2,3,4,5]


In [29]:
def vander_(ar,n):
    k=1
    arr=np.ones((n,n),dtype='int64')
    for i in range(1,n):
        for j in range(0,n):
            arr[i][j]=ar[j]**(k)
        k=k+1
    return arr;


In [30]:
final_array=vander_(array,n)
print("The final array is\n")
print(final_array)

The final array is

[[  1   1   1   1   1]
 [  1   2   3   4   5]
 [  1   4   9  16  25]
 [  1   8  27  64 125]
 [  1  16  81 256 625]]


### Ques 2- WINDOW MOVING AVERAGE QUESTION:


In [45]:
def window_average(arr,k):
    final=[]
    n=len(arr)
    for j in range(0,n-k+1):
        m=(arr[j]+arr[j+1]+arr[j+2]+arr[j+3])/k
        final.append(m)
    return final;

            

In [46]:

array=ast.literal_eval(input("Enter the array for window moving average\n"))
k=4
average_array=window_average(array,k)
print("The weighted average array is\n")
print(average_array)
        

Enter the array for window moving average
[10,20,30,40,50,60,70,80,90,100]
The weighted average array is

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


### Ques -3 - Write a function to find the window moving average for k=3

In [55]:
def window_average(arr,k):
    final=[]
    n=len(arr)
    sum=0
    for j in range(0,n-k+1):
        for i in range(0,k):
            sum=sum+(arr[j+i])
        m=sum/k
        final.append(m)
    return final;

In [56]:
arr=ast.literal_eval(input("Enter the array for window moving average\n"))
k=3
average_array=window_average(arr,k)
print("The weighted average array is\n")
print(average_array)

Enter the array for window moving average
[3,5,7,2,8,10,11,65,72,81,99,100,150]
The weighted average array is

[5.0, 9.666666666666666, 15.333333333333334, 22.0, 31.666666666666668, 60.333333333333336, 109.66666666666667, 182.33333333333334, 266.3333333333333, 359.6666666666667, 476.0]


In [57]:
print(len(arr))
print(len(average_array))

13
11
